# Generated by Django 2.0.8 on 2018-08-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgearea',
            options={'verbose_name': 'Knowledge Area', 'verbose_name_plural': 'Knowledge Areas'},
        ),
        migrations.AddField(
            model_name='knowledgeareaindexpage',
            name='knowledge_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.KnowledgeArea'),
        ),
        migrations.AddField(
            model_name='knowledgeareapage',
            name='abstract',
            field=models.TextField(blank=True, help_text='Text to describe the article'),
        ),
    ]
