# Generated by Django 2.0.8 on 2018-08-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180801_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeareaindexpage',
            name='knowledge_area',
            field=models.ForeignKey(help_text='Select a PMI knowledge area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.KnowledgeArea'),
        ),
    ]
